### ISSUE TITLE
Add serialization support

### ISSUE THREAD

**Issue by LegNeato** [panicbit/rust-gob#2]
I actually have this working, am cleaning it up and will put up a PR. Fair warning, it is a giant change.

**Comment by panicbit** [comment]
You've probably wasted your time :disappointed: , there's a more actively maintained implementation here: https://github.com/srijs/rust-gob

**Comment by LegNeato** [comment]
All good, I did it as an exercise :-D

**Comment by panicbit** [comment]
That's how this started out too :)
